# Generated by Django 4.1.2 on 2022-12-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_set_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0
            ),
        ),
    ]
