# Generated by Django 4.1.4 on 2023-01-25 13:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_follower_follower_unique_user'),
        ('main', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(
                related_name='content_makers', through='action.Follower', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
