# Generated by Django 4.1.4 on 2023-01-26 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_alter_follower_options_alter_follower_follower'),
        ('main', '0007_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(
                related_name='followers', through='action.Follower', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
