# Generated by Django 4.1.4 on 2023-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_user_followers_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Unknown'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='пол'
            ),
        ),
    ]
