# Generated by Django 4.1.4 on 2023-01-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(choices=[(1, 'Нравится'), (-1, 'Не нравится')]),
        ),
    ]
