# Generated by Django 4.1.4 on 2023-01-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_follower_follower_unique_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['content_maker']},
        ),
    ]
