# Generated by Django 4.1.4 on 2023-01-26 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action', '0004_alter_follower_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='following_to',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
