# Generated by Django 4.1.4 on 2023-01-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('action', '0006_remove_follower_unique_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='content_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='following_set',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
