# Generated by Django 4.1.4 on 2023-01-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
